### ISSUE TITLE
Genesis test checklist

### ISSUE THREAD

**Issue by immartian** [Musicoin/go-musicoin#11]
- [x] New [spec](https://github.com/Musicoin/go-musicoin/wiki/The-changes-of-Musicoin-Blockchain-from-Ethereum) 
- [x] Rebuild with changing bin from geth to gmc
- [x] Setting up 2 basic boot nodes 
- [x] testing gmc clients on discovering and syncing
- [x] defining new Parity spec into mc.json
- [x] Parity syncing test
- [x] Orbiter test  (http://104.199.113.25:3000/home )
- [x] tx test with stress
- [x] smart contracts test 
- [x] gas limitation test
- [x] CI and deployment test, musicoin.org, api.musicoin.org and orbiter.musicoin.org 
- [x] final test from scratch (redo the check list to make sure they work as expected)
- [x] ready to release

**Comment by immartian** [comment]
There will be some boot nodes set up in the new chain, the boot nodes are different from full-fledged node,running much more lightweighted peer discovering protocol. It will help connect more nodes once a new peer join the network and balance the connectivity without putting big throughput into one/two peers.

**Comment by immartian** [comment]
two big issues found before final testing: 
1. there's a split chain after running for several days
2. the bootnodes not serving for musicoin network only but the whole ethereum network, which leads to a polluted nodes pool and malfunctioning to serve musicoin network with new peers.

**Comment by immartian** [comment]
trying to switch to Ethereum Classic to see if it's the DAO-hardfork reason leads to this inconsistency, it's very much related from speculation by far.  Damn the DAO and Ethereum Foundation.

**Comment by immartian** [comment]
got some positive test result with ETC, the same time found the key issue with ETH geth as well, nevertheless, may stick with ETC for it's neatness.

**Comment by immartian** [comment]
The final sequence on 2/10:

- [ ] Confirm boot nodes are running properly, double confirmation
- [ ] Running up 3 seed nodes from scratch, double confirm they are connected to each other
- [ ] Running up 6 miners to  bootstrap the network, make sure they are all connected and then kickoff mining simultaneously 
- [ ] Running up orbiter node, in parity and confirm it's connected with other nodes (how?)
- [ ] Release final 

let me know ur ideas, @phiferd

**Comment by phiferd** [comment]
We will also need to capture accounts and their credentials and initiate some transactions on the network.  If we have the accounts ahead of time, I should be able to get most of the work done for api.musicoin.org.

**Comment by immartian** [comment]
np
